# Generated by Django 5.2 on 2026-04-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'unique_together': {('organization', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, verbose_name='código de lote')),
                ('fecha_elaboracion', models.DateField(blank=True, null=True, verbose_name='fecha de elaboración')),
                ('fecha_caducidad', models.DateField(db_index=True, verbose_name='fecha de caducidad')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad inicial')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad disponible')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo unitario')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_caducidad', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada / Compra'), ('SALIDA', 'Salida / Venta'), ('AJUSTE', 'Ajuste de Inventario'), ('MERMA', 'Merma / Vencido')], max_length=15, verbose_name='tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positivo para entradas, negativo para salidas', max_digits=10, verbose_name='cantidad')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Factura X, Pedido Y', max_length=100, verbose_name='documento referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.lote')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU / Código')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio_base', models.DecimalField(blank=True, decimal_places=2, help_text='Precio sugerido de venta. Puede modificarse en cada pedido.', max_digits=12, null=True, verbose_name='precio base')),
                ('unidad', models.CharField(blank=True, help_text='Ej: unidad, kg, litro, caja', max_length=30, verbose_name='unidad de medida')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='peso por unidad (kg)')),
                ('exento_iva', models.BooleanField(default=True, help_text='Si es falso, se le cobrará el 16% de IVA en la facturación y pedidos.', verbose_name='exento de IVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.categoriaproducto', verbose_name='categoría')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
                'unique_together': {('organization', 'sku')},
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='lote',
            unique_together={('producto', 'codigo_lote')},
        ),
    ]
