# Generated by Django 5.2 on 2026-04-07 18:30

import django.db.models.deletion
from django.db import migrations, models


def migrar_unidad_texto_a_fk(apps, schema_editor):
    """
    Para cada organización, crea UnidadMedida desde los valores únicos del CharField
    Producto.unidad, luego enlaza cada producto al registro creado.
    Solo procesa productos que tienen texto en unidad pero no tienen unidad_medida asignada.
    """
    Producto = apps.get_model('productos', 'Producto')
    UnidadMedida = apps.get_model('configuracion', 'UnidadMedida')
    Organization = apps.get_model('accounts', 'Organization')

    for org in Organization.objects.all():
        # Recopilar valores únicos de unidad para esta org
        valores = (
            Producto.objects
            .filter(organization=org, unidad_medida__isnull=True)
            .exclude(unidad='')
            .values_list('unidad', flat=True)
            .distinct()
        )

        for texto in valores:
            texto = texto.strip()
            if not texto:
                continue

            # Crear UnidadMedida si no existe (por simbolo)
            um, _ = UnidadMedida.objects.get_or_create(
                organization=org,
                simbolo=texto[:10],  # límite del campo simbolo
                defaults={
                    'nombre': texto,
                    'tipo': 'CANTIDAD',
                    'activa': True,
                },
            )

            # Enlazar productos
            Producto.objects.filter(
                organization=org,
                unidad=texto,
                unidad_medida__isnull=True,
            ).update(unidad_medida=um)


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('productos', '0002_fix_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='configuracion.unidadmedida', verbose_name='unidad de medida'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.CharField(blank=True, help_text='Campo heredado. Usar unidad_medida (FK) cuando esté configurado.', max_length=30, verbose_name='unidad de medida (texto)'),
        ),
        migrations.RunPython(
            migrar_unidad_texto_a_fk,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
