# Generated by Django 5.2 on 2026-04-05 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_add_peso_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, verbose_name='código de lote')),
                ('fecha_elaboracion', models.DateField(blank=True, null=True, verbose_name='fecha de elaboración')),
                ('fecha_caducidad', models.DateField(db_index=True, verbose_name='fecha de caducidad')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad inicial')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad disponible')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo unitario')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_caducidad', 'created_at'],
                'unique_together': {('producto', 'codigo_lote')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada / Compra'), ('SALIDA', 'Salida / Venta'), ('AJUSTE', 'Ajuste de Inventario'), ('MERMA', 'Merma / Vencido')], max_length=15, verbose_name='tipo')),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positivo para entradas, negativo para salidas', max_digits=10, verbose_name='cantidad')),
                ('referencia', models.CharField(blank=True, help_text='Ej: Factura X, Pedido Y', max_length=100, verbose_name='documento referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='productos.lote')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
