# Generated by Django 5.2 on 2026-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_unidad_medida_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alerta cuando el stock total cae bajo este valor. 0 = sin alerta.', max_digits=10, verbose_name='Stock mínimo'),
        ),
    ]
