# Generated by Django 5.2 on 2026-04-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_producto_deleted_at_producto_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='exento_iva',
            field=models.BooleanField(default=True, help_text='Si es falso, se le cobrará el 16% de IVA en la facturación y pedidos.', verbose_name='exento de IVA'),
        ),
    ]
