# Generated by Django 5.2 on 2026-04-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('contacto', models.CharField(blank=True, max_length=200, verbose_name='persona de contacto')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('direccion', models.TextField(blank=True, verbose_name='dirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
                'unique_together': {('organization', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='N° pedido')),
                ('fecha_pedido', models.DateField(db_index=True, verbose_name='fecha del pedido')),
                ('fecha_entrega', models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de entrega estimada')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('En Proceso', 'En Proceso'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], db_index=True, default='Pendiente', max_length=20, verbose_name='estado')),
                ('estado_despacho', models.CharField(choices=[('Pendiente Despacho', 'Pendiente Despacho'), ('Programado', 'Programado'), ('En Tránsito', 'En Tránsito'), ('Despachado', 'Despachado'), ('Devuelto', 'Devuelto')], db_index=True, default='Pendiente Despacho', max_length=30, verbose_name='estado de despacho')),
                ('ref_competencia', models.CharField(blank=True, max_length=500, verbose_name='referencia competencia')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.cliente', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido', '-created_at'],
                'unique_together': {('organization', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=50, verbose_name='número de factura')),
                ('fecha_factura', models.DateField(verbose_name='fecha de factura')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_creadas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_factura'],
            },
        ),
        migrations.CreateModel(
            name='PedidoEstadoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=30, verbose_name='estado anterior')),
                ('estado_nuevo', models.CharField(max_length=30, verbose_name='estado nuevo')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de cambio')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='pedidos.pedido')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de pedido',
                'verbose_name_plural': 'Logs de pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200, verbose_name='producto')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('exento_iva', models.BooleanField(default=True, verbose_name='exento de IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Ítem del pedido',
                'verbose_name_plural': 'Ítems del pedido',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva'), models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='precio_positivo')],
            },
        ),
    ]
