# Generated by Django 5.2 on 2026-04-07 18:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
        ('pedidos', '0002_fix_missing_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = pago contado', verbose_name='días de crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 = sin límite', max_digits=12, verbose_name='límite de crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lista_precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='configuracion.listaprecio', verbose_name='lista de precios'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lista_precio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='configuracion.listaprecio', verbose_name='lista de precios aplicada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='configuracion.metodopago', verbose_name='método de pago'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='zona_despacho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='configuracion.zonadespacho', verbose_name='zona de despacho'),
        ),
    ]
