# Generated by Django 5.2 on 2026-04-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_factura_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('En Proceso', 'En Proceso'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], db_index=True, default='Pendiente', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_despacho',
            field=models.CharField(choices=[('Pendiente Despacho', 'Pendiente Despacho'), ('Programado', 'Programado'), ('En Tránsito', 'En Tránsito'), ('Despachado', 'Despachado'), ('Devuelto', 'Devuelto')], db_index=True, default='Pendiente Despacho', max_length=30, verbose_name='estado de despacho'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='fecha de entrega estimada'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateField(db_index=True, verbose_name='fecha del pedido'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='pedidoitem',
            constraint=models.CheckConstraint(condition=models.Q(('precio__gte', 0)), name='precio_positivo'),
        ),
    ]
