# Generated by Django 5.2 on 2026-04-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_cliente_deleted_at_cliente_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='exento_iva',
            field=models.BooleanField(default=True, verbose_name='exento de IVA'),
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA'),
        ),
    ]
