# Generated by Django 5.2 on 2026-04-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisor_asignado',
            field=models.ForeignKey(blank=True, help_text='Indica a qué supervisor rinde cuentas este vendedor.', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedores_asignados', to=settings.AUTH_USER_MODEL, verbose_name='supervisor asignado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('vendedor', 'Vendedor'), ('facturador', 'Facturador')], default='vendedor', max_length=20, verbose_name='rol'),
        ),
    ]
