# Generated by Django 5.2 on 2026-04-06 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='código')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
                'unique_together': {('organization', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='TasaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('tasa_bs_por_usd', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='tasa Bs/USD')),
                ('fuente', models.CharField(blank=True, help_text='Ej: BCV, paralelo', max_length=50, verbose_name='fuente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-fecha'],
                'unique_together': {('organization', 'fecha', 'fuente')},
            },
        ),
        migrations.CreateModel(
            name='VentaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField(help_text='Primer día del mes', verbose_name='periodo')),
                ('vendedor_nombre', models.CharField(max_length=200, verbose_name='nombre vendedor')),
                ('producto_nombre', models.CharField(max_length=200, verbose_name='nombre producto')),
                ('codigo_producto', models.CharField(blank=True, max_length=50, verbose_name='código producto')),
                ('zona_nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre zona')),
                ('canal', models.CharField(blank=True, choices=[('DIRECTO', 'Directo'), ('DISTRIBUCIÓN', 'Distribución')], max_length=30, verbose_name='canal')),
                ('distribucion', models.CharField(blank=True, max_length=200, verbose_name='distribución')),
                ('plan_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan cantidad')),
                ('plan_precio_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan precio USD')),
                ('plan_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan venta USD')),
                ('plan_costo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan costo USD')),
                ('plan_margen_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan margen USD')),
                ('plan_flete_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan flete USD')),
                ('plan_gastos_fin_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan gastos financieros USD')),
                ('plan_impuestos_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan impuestos USD')),
                ('plan_logisticos_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan logísticos USD')),
                ('plan_gastos_ventas_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan gastos ventas USD')),
                ('plan_margen_neto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='plan margen neto USD')),
                ('real_cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real cantidad')),
                ('real_venta_ves', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='real venta VES')),
                ('real_venta_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real venta USD')),
                ('real_costo_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real costo USD')),
                ('real_flete_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real flete USD')),
                ('real_gastos_fin_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real gastos financieros USD')),
                ('real_impuestos_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real impuestos USD')),
                ('real_logisticos_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real logísticos USD')),
                ('real_gastos_ventas_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real gastos ventas USD')),
                ('real_margen_neto_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='real margen neto USD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_mensuales', to='productos.producto')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_mensuales', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuotas.zona')),
            ],
            options={
                'verbose_name': 'Venta mensual',
                'verbose_name_plural': 'Ventas mensuales',
                'ordering': ['-periodo', 'vendedor_nombre'],
                'indexes': [models.Index(fields=['organization', 'periodo'], name='cuotas_vent_organiz_884d53_idx'), models.Index(fields=['organization', 'zona_nombre'], name='cuotas_vent_organiz_20a752_idx'), models.Index(fields=['organization', 'vendedor_nombre'], name='cuotas_vent_organiz_af0be3_idx')],
            },
        ),
    ]
