# Generated by Django 5.2 on 2026-04-07 23:42

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configuracion', '0003_alter_tasacambio_id'),
        ('pedidos', '0003_cliente_credito_pedido_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='N° cotización')),
                ('fecha', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Fecha')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Válida hasta')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Enviada', 'Enviada al cliente'), ('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('Vencida', 'Vencida'), ('Convertida', 'Convertida a Pedido')], db_index=True, default='Borrador', max_length=15, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('condiciones', models.TextField(blank=True, help_text='Si vacío, usa los términos de ConfiguracionEmpresa', verbose_name='Términos y condiciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='pedidos.cliente', verbose_name='cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('lista_precio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='configuracion.listaprecio', verbose_name='lista de precios')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='configuracion.metodopago', verbose_name='método de pago')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('pedido_generado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='pedidos.pedido', verbose_name='pedido generado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones_vendedor', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
                ('zona_despacho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='configuracion.zonadespacho', verbose_name='zona de despacho')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200, verbose_name='producto')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('exento_iva', models.BooleanField(default=True, verbose_name='exento de IVA')),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto IVA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Ítem de cotización',
                'verbose_name_plural': 'Ítems de cotización',
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['organization', 'estado'], name='cotizacione_organiz_ad29fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['organization', 'fecha'], name='cotizacione_organiz_f118b5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotizacion',
            unique_together={('organization', 'numero')},
        ),
    ]
