# Generated by Django 5.2 on 2026-04-07 23:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pedidos', '0003_cliente_credito_pedido_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=datetime.date.today, verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto USD')),
                ('metodo', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('ZELLE', 'Zelle'), ('DIVISA', 'Divisas en efectivo'), ('OTRO', 'Otro')], default='TRANSFERENCIA', max_length=15, verbose_name='Método')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='N° referencia / comprobante')),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='pedidos.cliente', verbose_name='cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
