# Generated by Django 5.2 on 2026-03-11 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenciaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha del hallazgo')),
                ('producto', models.CharField(max_length=200, verbose_name='producto')),
                ('competidor', models.CharField(max_length=200, verbose_name='competidor')),
                ('precio_comp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='precio del competidor')),
                ('precio_nuestro', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='nuestro precio')),
                ('accion_tomada', models.TextField(blank=True, verbose_name='acción tomada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cliente', verbose_name='cliente involucrado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'Registro de competencia',
                'verbose_name_plural': 'Registros de competencia',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
