# Generated by Django 5.2 on 2026-04-07 15:49

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre comercial')),
                ('rif', models.CharField(blank=True, max_length=20, verbose_name='RIF / NIT')),
                ('direccion_fiscal', models.TextField(blank=True, verbose_name='Dirección fiscal')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo de la empresa')),
                ('moneda_principal', models.CharField(choices=[('USD', 'Dólar estadounidense'), ('VES', 'Bolívar venezolano'), ('EUR', 'Euro'), ('COP', 'Peso colombiano')], default='USD', max_length=3, verbose_name='Moneda principal')),
                ('zona_horaria', models.CharField(default='America/Caracas', max_length=50, verbose_name='Zona horaria')),
                ('prefijo_pedido', models.CharField(default='PED', max_length=10, verbose_name='Prefijo de pedido')),
                ('digitos_pedido', models.PositiveSmallIntegerField(default=6, help_text='Ej: 6 → PED-000001', verbose_name='Dígitos en número de pedido')),
                ('siguiente_numero_pedido', models.PositiveIntegerField(default=1, verbose_name='Siguiente número de pedido')),
                ('prefijo_factura', models.CharField(default='FAC', max_length=10, verbose_name='Prefijo de factura')),
                ('siguiente_numero_factura', models.PositiveIntegerField(default=1, verbose_name='Siguiente número de factura')),
                ('prefijo_cotizacion', models.CharField(default='COT', max_length=10, verbose_name='Prefijo de cotización')),
                ('siguiente_numero_cotizacion', models.PositiveIntegerField(default=1, verbose_name='Siguiente número de cotización')),
                ('iva_por_defecto', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, verbose_name='Tasa de IVA por defecto (%)')),
                ('metodo_valoracion_inventario', models.CharField(choices=[('FEFO', 'FEFO — Primero en vencer, primero en salir'), ('FIFO', 'FIFO — Primero en entrar, primero en salir'), ('PROMEDIO', 'Costo promedio ponderado')], default='FEFO', max_length=10, verbose_name='Método de valoración de inventario')),
                ('permitir_stock_negativo', models.BooleanField(default=False, verbose_name='Permitir ventas con stock negativo')),
                ('dias_credito_default', models.PositiveSmallIntegerField(default=30, verbose_name='Días de crédito por defecto')),
                ('limite_credito_default', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Límite de crédito por defecto (0 = sin límite)')),
                ('terminos_condiciones', models.TextField(blank=True, help_text='Aparece al pie de facturas y cotizaciones', verbose_name='Términos y condiciones')),
                ('nota_factura', models.TextField(blank=True, help_text='Campo libre adicional en facturas', verbose_name='Nota de factura')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
                'verbose_name_plural': 'Configuraciones de empresa',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('CONTADO', 'Contado (efectivo o equivalente)'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia bancaria'), ('CHEQUE', 'Cheque'), ('MIXTO', 'Mixto')], max_length=15, verbose_name='Tipo')),
                ('dias_credito', models.PositiveSmallIntegerField(default=0, help_text='Solo aplica para tipo CREDITO', verbose_name='Días de crédito')),
                ('activa', models.BooleanField(default=True, verbose_name='Activo')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Método de pago',
                'verbose_name_plural': 'Métodos de pago',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ZonaDespacho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('costo_base_flete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo base de flete')),
                ('dias_entrega_estimados', models.PositiveSmallIntegerField(default=1, verbose_name='Días de entrega estimados')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Zona de despacho',
                'verbose_name_plural': 'Zonas de despacho',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Precio Mayorista', max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(help_text='Ej: B', max_length=5, verbose_name='Código')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento sobre precio base del producto', max_digits=5, verbose_name='Descuento (%)')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('es_default', models.BooleanField(default=False, help_text='Se aplica a clientes sin lista asignada', verbose_name='Lista por defecto')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Lista de precios',
                'verbose_name_plural': 'Listas de precios',
                'ordering': ['codigo'],
                'unique_together': {('organization', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Ej: Kilogramo', max_length=50, verbose_name='Nombre')),
                ('simbolo', models.CharField(help_text='Ej: kg', max_length=10, verbose_name='Símbolo')),
                ('tipo', models.CharField(choices=[('PESO', 'Peso'), ('VOLUMEN', 'Volumen'), ('LONGITUD', 'Longitud'), ('AREA', 'Área'), ('CANTIDAD', 'Cantidad'), ('TIEMPO', 'Tiempo')], max_length=10, verbose_name='Tipo')),
                ('es_base', models.BooleanField(default=False, help_text='La unidad base tiene factor_conversion = 1', verbose_name='Es unidad base del tipo')),
                ('factor_conversion', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='Relativo a la unidad base del mismo tipo. Ej: 1 caja = 12 unidades → factor 12', max_digits=15, verbose_name='Factor de conversión')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'ordering': ['tipo', 'nombre'],
                'indexes': [models.Index(fields=['organization', 'tipo', 'activa'], name='configuraci_organiz_f98286_idx')],
                'unique_together': {('organization', 'simbolo')},
            },
        ),
    ]
