# Generated by Django 5.2 on 2026-04-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_tasacambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasacambio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
