# Generated by Django 5.2 on 2026-03-22 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pedidos', '0003_factura_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, verbose_name='placa')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='modelo')),
                ('capacidad_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='capacidad (kg)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chofer_habitual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_chofer', to=settings.AUTH_USER_MODEL, verbose_name='chofer habitual')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['placa'],
                'unique_together': {('organization', 'placa')},
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha del viaje')),
                ('estado', models.CharField(choices=[('Programado', 'Programado'), ('En Ruta', 'En Ruta'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], default='Programado', max_length=20, verbose_name='estado')),
                ('km_recorridos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='km recorridos')),
                ('costo_flete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='costo de flete')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes_chofer', to=settings.AUTH_USER_MODEL, verbose_name='chofer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viajes_creados', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flotas.vehiculo', verbose_name='vehículo')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViajeDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_estimado_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='peso estimado (kg)')),
                ('orden_entrega', models.PositiveSmallIntegerField(default=0, verbose_name='orden de entrega')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaje_detalles', to='pedidos.pedido')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='flotas.viaje')),
            ],
            options={
                'verbose_name': 'Detalle de viaje',
                'verbose_name_plural': 'Detalles de viaje',
                'ordering': ['orden_entrega'],
                'unique_together': {('viaje', 'pedido')},
            },
        ),
    ]
