# Generated by Django 5.2 on 2026-04-08 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pedidos', '0003_cliente_credito_pedido_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha de visita')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('telefonica', 'Telefónica'), ('virtual', 'Virtual / Videollamada')], default='presencial', max_length=20, verbose_name='tipo de visita')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('objetivo', models.TextField(blank=True, verbose_name='objetivo de la visita')),
                ('resultado', models.TextField(blank=True, verbose_name='resultado / notas')),
                ('proxima_visita', models.DateField(blank=True, null=True, verbose_name='próxima visita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='pedidos.cliente', verbose_name='cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
            ],
            options={
                'verbose_name': 'Visita Comercial',
                'verbose_name_plural': 'Visitas Comerciales',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'fecha'], name='visitas_vis_organiz_87965b_idx'), models.Index(fields=['organization', 'vendedor'], name='visitas_vis_organiz_2c0bc5_idx'), models.Index(fields=['organization', 'estado'], name='visitas_vis_organiz_0b3be0_idx')],
            },
        ),
    ]
