# Generated by Django 5.2 on 2026-04-08 00:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pedidos', '0003_cliente_credito_pedido_fks'),
        ('productos', '0003_producto_unidad_medida_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True, default=datetime.date.today, verbose_name='fecha')),
                ('motivo', models.CharField(choices=[('DEFECTO', 'Producto defectuoso'), ('ERROR_PEDIDO', 'Error en pedido'), ('NO_SOLICITADO', 'Producto no solicitado'), ('DANO_TRANSPORTE', 'Daño en transporte'), ('VENCIDO', 'Producto vencido/próximo a vencer'), ('OTRO', 'Otro motivo')], max_length=20, verbose_name='motivo')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada')], db_index=True, default='Pendiente', max_length=12, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('monto_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto nota de crédito')),
                ('reingresar_inventario', models.BooleanField(default=True, verbose_name='reingresar al inventario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='pedidos.cliente', verbose_name='cliente')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones', to='pedidos.pedido', verbose_name='pedido origen')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=200, verbose_name='producto')),
                ('sku', models.CharField(blank=True, max_length=50, verbose_name='SKU')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio unitario')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='devoluciones.devolucion', verbose_name='devolución')),
                ('lote_reingreso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='productos.lote', verbose_name='lote de reingreso')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.organization', verbose_name='organización')),
            ],
            options={
                'verbose_name': 'Ítem de devolución',
                'verbose_name_plural': 'Ítems de devolución',
            },
        ),
    ]
